### ISSUE TITLE
running ./docker-record "container name" --replay fails

### ISSUE THREAD

**Issue by ahojjati** [citostyle/docker-record#2]
Traceback (most recent call last):
  File "./docker-record", line 167, in <module>
    replay(container)
  File "./docker-record", line 62, in replay
    commands = read_session(container, COMMAND_FILENAME)
  File "./docker-record", line 131, in read_session
    return copy(container, SESSION_PATH.format(filename = filename)).split("\n")
  File "./docker-record", line 153, in copy
    response = client.copy(container, path)
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, _args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 89, in copy
    self._raise_for_status(res)
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 141, in _raise_for_status
    raise errors.NotFound(e, response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("client and server don't have same version (client : 1.20, server: 1.18)")

---

Running "docker.io version" indicates that both client and server versions are matching.

**Comment by ahojjati** [comment]
You should upgrade to the latest version of "docker-engine", below shows the process:

$ apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys\ 58118E89F3A912897C070ADBF76221572C52609D

$ vim /etc/apt/sources.list.d/docker.list

delete everything in "docker.list" and add:

!# Ubuntu Trusty 
deb https://apt.dockerproject.org/repo ubuntu-trusty main

$ apt-get update

$ apt-get purge lxc-docker*

$ apt-get install docker-engine

---

Running the above successfully will result in have your "./docker-record "container name" --replay" to work fine.
